### ISSUE TITLE
页头部位用户下拉栏上下标志

### ISSUE THREAD

**Issue by Crazyya** [shawhu/ProPlay#21]
![ui1](https://cloud.githubusercontent.com/assets/11494538/6776435/4bddbc34-d179-11e4-8380-1319b24a8ea2.png)
![ui2](https://cloud.githubusercontent.com/assets/11494538/6776436/4be75eb0-d179-11e4-8747-e4916692e5d7.png)
       用户下拉栏的指向方向是不是改成all instruments那个好些？不然的话这个∧符号结果是下拉就很怪异了。
http://cn.take7music.com:81/Store.aspx
http://take7music.com/Store.aspx

**Comment by mingwu** [comment]
done

**Comment by Crazyya** [comment]
Confirm the correct
