### ISSUE TITLE
SIGN UP创建时可以用中文成功创建

### ISSUE THREAD

**Issue by Crazyya** [shawhu/ProPlay#26]
![default](https://cloud.githubusercontent.com/assets/11494538/6820511/fa6849b2-d30a-11e4-98db-3477648cc00e.png)
这个帐号密码是：俺俺俺俺俺俺  创建的时候直接复制粘贴在密码栏，可以成功创建。
![default](https://cloud.githubusercontent.com/assets/11494538/6820529/1bf7eeb6-d30b-11e4-9eb9-57eefd8787fa.png)
登录的时候同样的密码帐号提示email or password错误，是否改一下让他中文密码的时候提示输入正确的密码，我在google注册试了一下复制粘贴中文密码，就有限制提示。
![google](https://cloud.githubusercontent.com/assets/11494538/6820631/00e3d3dc-d30c-11e4-9801-8f7ec14369cf.png)

SIGN UP地址链接:https://take7music.com/SignUp.aspx

**Comment by Crazyya** [comment]
还有一个就是注册成功后提示Please CLICK THE ACTIVATION LINK sent to the following 

address，但是我在下面没有找到链接，是到了邮件里面去看才发现链接在邮件里，可是网页没有，是不是换一下，还有一个就是邮件是被邮箱自动标记成广告邮件的。

**Comment by shawhu** [comment]
没明白这是什么意思，错在哪里。

bug的标题应该可以表示这个错误错在哪里 

比如以下标题是好的标题

用户不能通过facebook登录
不能用中国信用卡支付
等等



萧和 Harry Xiao @shawhu

**Comment by shawhu** [comment]
中文作为密码是允许的


萧和 Harry Xiao @shawhu

**Comment by Crazyya** [comment]
了解了。

**Comment by Crazyya** [comment]
了解了。
