### ISSUE TITLE
Birthday可以手动输入，且只要格式正确输入选项内没有的年份也可以成功注册

### ISSUE THREAD

**Issue by Crazyya** [shawhu/ProPlay#27]
例如在Birthday手动输入01/01/1100,就可以成功注册，不排除用户在注册的时候不注意碰到某个键输入的情况。

还有一个情况就是在Birthday中手动输入错误格式的日期，例如123/123/123，点击注册按钮后可以明显看到按钮颜色变成浅灰色，然后页面就再无任何反应，没有跳转没有提示错误，怎么点SIGN UP都没有一点反应。
![default](https://cloud.githubusercontent.com/assets/11494538/6820893/0625351e-d30e-11e4-89a9-707fc392e4bf.png)
![default](https://cloud.githubusercontent.com/assets/11494538/6820896/09e9effa-d30e-11e4-97ca-82fe453e7a96.png)

![default](https://cloud.githubusercontent.com/assets/11494538/6820899/0f6fcdb4-d30e-11e4-9002-0860232ce39e.png)
点击后和点击前唯一的变化就是按钮颜色了。

SIGN UP地址链接：https://take7music.com/SignUp.aspx

**Comment by Crazyya** [comment]
我浏览google的注册网页，有提示的，如果错了会有提示

**Comment by mingwu** [comment]
格式不正确现在有提示了。

**Comment by Crazyya** [comment]
confirm
