### ISSUE TITLE
有个问题，那些推特、facebook的关联链接貌似都是标记成刷新当前页面

### ISSUE THREAD

**Issue by Crazyya** [shawhu/ProPlay#30]
有个问题，那些推特、facebook的关联链接貌似都是标记成刷新当前页面
![2](https://cloud.githubusercontent.com/assets/11494538/6839982/e221d926-d3ab-11e4-9332-29f43d118645.png)
我查了一下，发现所有的超链接，除了登录页面的关联facebook的链接有效以外，别的地址全是指向当前页面，就有个问题，这个是属于bug?还是只是现在还没有把功能写上去？

**Comment by shawhu** [comment]
属于已知问题，我们还没实现

萧和 Harry Xiao @shawhu

**Comment by Crazyya** [comment]
confirm。
