### ISSUE TITLE
Serch页面不能打开乐器分类信息

### ISSUE THREAD

**Issue by Crazyya** [shawhu/ProPlay#33]
![serch](https://cloud.githubusercontent.com/assets/11494538/6861826/ff4cb6f2-d477-11e4-8c21-6cdbc5000b64.png)

链接地址：http://take7music.com/SearchResult.aspx?keyword=

**Comment by mingwu** [comment]
乐器分类信息应该是没有的。

**Comment by Crazyya** [comment]
confirm
