### ISSUE TITLE
注册页面现在所有的报错全部成为日期错误，且更正后再点击注册按钮不能正常注册

### ISSUE THREAD

**Issue by Crazyya** [shawhu/ProPlay#34]
更改日期可以正常报错后，别的错误也都全部提示为日期错误，并且在更正错误之后再点击注册按钮页面无响应，不能正常注册。
![default](https://cloud.githubusercontent.com/assets/11494538/6863225/1c3b3328-d488-11e4-86e6-e6cad9ca4571.png)
这里是密码两次输入的都不一样他提示了日期错误，然后我更改为两次密码输入都为1234567后再点击注册，页面无响应，不能注册，错误提示也不更改。

链接地址：http://take7music.com/SignUp.aspx

**Comment by Crazyya** [comment]
重新刷新完毕后，全部输入正确后不能注册了。
![default](https://cloud.githubusercontent.com/assets/11494538/6863263/01767f24-d489-11e4-8d4b-eb951b453369.png)
这里我所有信息输入都没错，他提示日期错误，并且不能注册

**Comment by shawhu** [comment]
这是一个大问题，要麻烦wuming尽快

萧和 Harry Xiao @shawhu

**Comment by Crazyya** [comment]
confirm, has been changed.
